# Homework 1

## Q1

In [1]:
import pandas as pd
print(pd.__version__)

3.0.6


## Q2

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [3]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2


In [4]:
len(df)

10000

## Q3

In [5]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

df.nunique()

## Q4

In [6]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5

In [7]:
df.fuel_efficiency_mpg.max()

np.float64(41.2)

## Q6

In [8]:
df.horsepower.median()

np.float64(254.0)

In [9]:
df['horsepower'].value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ... 
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [10]:
df2 = df.copy()
df2['horsepower'] = df2.horsepower.fillna(252)

In [11]:
df2.horsepower.median()

np.float64(252.0)

## Q7

In [12]:
import numpy as np

In [13]:
cars_asia_df = df2[df2['origin'] == 'Asia'][['vehicle_weight','model_year']].reset_index(drop = True)

In [14]:
print(cars_asia_df.head(7))
X_list = cars_asia_df.head(7).values

   vehicle_weight  model_year
0            4240        1996
1            4310        1992
2            4230        1997
3            4420        1978
4            3950        2007
5            4750        2021
6            4450        2019


In [15]:
X = np.array(X_list)

In [16]:
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]


In [17]:
XTX = X.T.dot(X)

In [18]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [19]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [20]:
print(np.linalg.inv(XTX))

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]


In [26]:
w = np.linalg.inv(XTX).dot(X.T) * y
print(w)

[[-0.27509119 -0.02155228 -0.22895733  0.35996837 -1.18162927  1.21328359
   0.27042587]
 [ 0.67427208  0.13904122  0.5529994  -0.71637186  2.63152339 -2.54924935
  -0.49946567]]


In [27]:
np.sum(w)

np.float64(0.36919696904925475)